FROM golang
RUN mkdir /app 
ADD . /app/
WORKDIR /app 
RUN go build -o main server.go
ENTRYPOINT ["./main"]
EXPOSE 5300

# FROM golang:alpine as builder
# RUN mkdir /build 
# ADD . /build/
# WORKDIR /build 
# RUN go build -o main server.go
# FROM alpine
# RUN adduser -S -D -H -h /app appuser
# USER appuser
# COPY --from=builder /build/main /app/
# WORKDIR /app
# CMD ["./main"]  